[build]
buildCommand = "npm install && pip install -r requirements.txt"

[deploy]
startCommand = "node whatsapp_otp.js & python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
startCommand = "node whatsapp_otp.js & python bot.py"
